apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
  creationTimestamp: null
  name: dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: dev project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: dev
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: docker-desktop/kustomize/**/overlays/dev/config.json
      repoURL: https://github.com/oren-codefresh/codefresh-manifests
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argo-autopilot
        app.kubernetes.io/name: '{{appName}}'
      name: dev-{{userGivenName}}
      namespace: argocd
    spec:
      destination:
        namespace: '{{destNamespace}}'
        server: '{{destServer}}'
      project: dev
      source:
        path: docker-desktop/kustomize/{{appName}}/overlays/dev
        repoURL: https://github.com/oren-codefresh/codefresh-manifests
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
status: {}
